### ISSUE TITLE
missing autoload directory

### ISSUE THREAD

**Issue by gewthen** [activeingredient/ezComponents#1]
You are missing the autoload directory. Please make sure you have the entire ezComponents library, as it is mostly worthless without the entire package.

**Comment by activeingredient** [comment]
The Base package contains the autoload script. All packages rely on the base package.

**Comment by cedriclombardot** [comment]
if we make a escBase::autoload we have an exception Couldn't find autoload directory '.....lib/vendor/ezComponents/Base/src/../../autoload/' ....

```
// Integrate eZ Components
    $sf_ez_lib_dir = sfConfig::get('sf_lib_dir').'/vendor/ezComponents/';
    set_include_path($sf_ez_lib_dir.PATH_SEPARATOR.get_include_path());
    require_once($sf_ez_lib_dir.'/Base/src/base.php');
```

```
spl_autoload_register(array('ezcBase', 'autoload'));
```

**Comment by activeingredient** [comment]
I see the issue, the extra autoload folder is not in the SVN repo

**Comment by activeingredient** [comment]
Complete git repo here:
https://github.com/MDrollette/ezComponents-lite
